version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres18
    restart: always
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U school_user -d school_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: studentmanagement-app
    container_name: student-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/school_db
      DB_USERNAME: school_user
      DB_PASSWORD: password

volumes:
  postgres_data:
